# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "DMTR Consulting"

# A description of your site for social meta tag, search engines, and feed.xml
description: ""


# The subpath of your site, e.g. /blog, for generating urls
baseurl:
# baseurl: https://beingeorge.com/lancer-jekyll

navigation:
  - text: Home
    url: /#home
  - text: About DMTR
    url: /#aboutdmtr
  - text: About us
    url: /#aboutus
  - text: services
    url: /#services
#  - text: Portfolio
#    url: /#portfolio
  #- text: Blog
  #  url: /#blog
  - text: Contact
    url: /#contact

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://dmtr-consulting.github.io"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "DMTR Consulting"

# Social links in the site footer
linkedin_username: "dmtr"
whatsapp_username: "39xxxxxxxxxx"
email: "info@dmtrconsulting.com"
